### ISSUE TITLE
Absence of data

### ISSUE THREAD

**Issue by Abednego97** [revenol/LyDROO#2]
First of all, I'd like to thank you for the open source codes. If I may ask,  where is the data for the Tensorflow version of the LyDROO,  thy PyTorch is self generated , how about the Tensorflow version? Thank you.

**Comment by revenol** [comment]
Thanks for the comments. 
The test data is not necessary for LyDROO. All channels and data are randomly generated in the runtime. Therefore, LyDROOwithTF2conv.py is updated to keep the same as LyDROO.py in the revised version.

Meanwhile, another bug is discovered and fixed in memoryTF2conv.py.

Simply run LyDROOwithTF2conv.py will work now.

**Comment by Abednego97** [comment]
Thank you very much for your response.
